In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies=movies.merge(credits,on='title')
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movies=pd.DataFrame(movies,columns=['movie_id','title','overview','genres','keywords','cast','crew'])
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
movies['title'].value_counts()

title
The Host                                    4
Batman                                      4
Out of the Blue                             4
Pirates of the Caribbean: At World's End    1
Spectre                                     1
                                           ..
El Mariachi                                 1
Newlyweds                                   1
Signed, Sealed, Delivered                   1
Shanghai Calling                            1
My Date with Drew                           1
Name: count, Length: 4800, dtype: int64

In [8]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace=True)

In [12]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
movies.duplicated().sum()

np.int64(0)

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
import ast


def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
movies['genres'] = movies['genres'].apply(convert)

In [17]:
movies['keywords'] = movies['keywords'].apply(convert)

In [18]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [19]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i['name'])
            counter+=1
        else:      
            break
    return L

In [20]:
movies['cast'] = movies['cast'].apply(convert3)

In [21]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [22]:
movies['crew' ].iloc[0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [23]:
import ast

def fetch_director(text):
    try:
        if isinstance(text, str):
            text = ast.literal_eval(text)
        
        for person in text:
            if person.get('job') == 'Director':
                return [person['name']]  # ← wrap in a list
        return []
    
    except (ValueError, TypeError):
        return []

In [24]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [25]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [26]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [27]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [28]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])

In [29]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [30]:
movies['tags']=movies ['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [31]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."

In [32]:
movies=movies.drop(columns=['overview','genres','keywords','cast','crew'],inplace=False)
movies.head(1)

   movie_id   title                                               tags
0     19995  Avatar  [In, the, 22nd, century,, a, paraplegic, Marin...

In [33]:
movies['tags']=movies['tags'].apply(lambda x: " ".join(x).lower())

In [34]:
movies.head(3)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...

In [35]:
movies['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [36]:
movies['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski"

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vectors=cv.fit_transform(movies['tags']).toarray() # type: ignore
vectors.shape

(4806, 5000)

In [38]:
import numpy as np
# forcing full output in vscode
np.set_printoptions(threshold=np.inf) # type: ignore

# Now run again
cv.get_feature_names_out()

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '18', '18th', '18thcentury', '19', '1930s', '1940s', '1950s',
       '1960s', '1970s', '1980', '1980s', '1985', '1990s', '19th',
       '19thcentury', '20', '200', '2009', '20th', '21st', '23', '24',
       '25', '30', '300', '3d', '40', '50', '500', '60', '60s', '70',
       '70s', 'aaron', 'aaroneckhart', 'abandoned', 'abducted',
       'abigailbreslin', 'abilities', 'ability', 'able', 'aboard',
       'abuse', 'abusive', 'academy', 'accept', 'accepted', 'accepts',
       'access', 'accident', 'accidental', 'accidentally', 'accompanied',
       'accomplish', 'account', 'accountant', 'accused', 'ace', 'achieve',
       'act', 'acting', 'action', 'actionhero', 'actions', 'activist',
       'activities', 'activity', 'actor', 'actors', 'actress', 'acts',
       'actual', 'actually', 'adam', 'adams', 'adamsandler',
       'adamshankman', 'adaptation', 'adapted', 'addict', 'addicted',
       'addiction', 'adolescence', 'adopt', 'adopted', 'adoption',
       'adopts', 'adrienbrody', 'adult', 'adultanimation', 'adultery',
       'adulthood', 'adults', 'advantage', 'adventure', 'adventures',
       'advertising', 'advice', 'affair', 'affairs', 'affect',
       'affection', 'affections', 'afghanistan', 'africa', 'african',
       'africanamerican', 'aftercreditsstinger', 'afterlife', 'aftermath',
       'age', 'aged', 'agedifference', 'agency', 'agenda', 'agent',
       'agents', 'aggressive', 'aging', 'ago', 'agree', 'agrees', 'ahead',
       'aid', 'aidanquinn', 'aided', 'aids', 'ailing', 'air', 'airplane',
       'airplanecrash', 'airport', 'aka', 'al', 'alabama', 'alan',
       'alaska', 'albert', 'alcohol', 'alcoholic', 'alcoholism',
       'alecbaldwin', 'alex', 'alfredhitchcock', 'ali', 'alice', 'alien',
       'alieninvasion', 'alienlife', 'alienplanet', 'aliens', 'alike',
       'alive', 'allen', 'alliance', 'allied', 'allies', 'allow',
       'allows', 'ally', 'alongside', 'alpacino', 'alter', 'alternate',
       'alternative', 'alzheimer', 'amanda', 'amandapeet',
       'amandaseyfried', 'amateur', 'amazing', 'ambassador', 'ambition',
       'ambitious', 'ambulance', 'ambush', 'america', 'american',
       'americanabroad', 'americanfootball', 'americans', 'amid',
       'amidst', 'amnesia', 'amp', 'amsterdam', 'amusementpark', 'amy',
       'amyadams', 'amysmart', 'analyst', 'anarchiccomedy', 'ancient',
       'ancientrome', 'ancientworld', 'anderson', 'andiemacdowell',
       'andrew', 'android', 'andy', 'andygarcía', 'angel',
       'angelabassett', 'angeles', 'angelinajolie', 'angels', 'anger',
       'anglee', 'angry', 'animal', 'animalattack', 'animalhorror',
       'animals', 'animated', 'animation', 'anna', 'annafaris', 'anne',
       'annehathaway', 'annemoss', 'annettebening', 'annie',
       'anniversary', 'announces', 'annual', 'anonymity', 'answer',
       'answers', 'ant', 'antarctic', 'anthology', 'anthony',
       'anthonyanderson', 'anthonyhopkins', 'anthonymackie',
       'anthropomorphism', 'anti', 'antics', 'antihero', 'antoinefuqua',
       'antoniobanderas', 'antonyelchin', 'apart', 'apartheid',
       'apartment', 'ape', 'apes', 'apocalypse', 'apocalyptic',
       'apparent', 'apparently', 'appear', 'appears', 'apple',
       'appointed', 'apprentice', 'approach', 'approaches', 'approaching',
       'april', 'aquarium', 'arab', 'arch', 'archaeologist', 'archeology',
       'archer', 'architect', 'arctic', 'area', 'aren', 'arena',
       'argument', 'arise', 'aristocrat', 'armed', 'arms', 'army',
       'arnold', 'arnoldschwarzenegger', 'arrangedmarriage',
       'arrangement', 'arrest', 'arrested', 'arrival', 'arrive',
       'arrived', 'arrives', 'arriving', 'arrogant', 'art', 'arthur',
       'article', 'artificial', 'artificialintelligence', 'artist',
       'artistic', 'artists', 'arts', 'ashes', 'ashley', 'ashleyjudd',
       'ashtonkutcher', 'asia', 'aside', 'ask', 'asked', 'asking', 'asks',
       'aspirations', 'aspiring', 'assassin', 'assassinate',
       'assassination', 'assassins', 'assault', 'assigned', 'assignment',
       'assistant', 'assumes', 'asteroid', 'astronaut', 'astronauts',
       'asylum', 'athlete', 'atomicbomb', 'attack', 'attacked', 'attacks',
       'attempt', 'attempting', 'attempts', 'attending', 'attends',
       'attention', 'attitude', 'attorney', 'attracted', 'attraction',
       'attractive', 'audience', 'audiences', 'audition', 'august',
       'aunt', 'austin', 'australia', 'australian', 'author',
       'authorities', 'authority', 'autism', 'auto', 'avenge', 'average',
       'avoid', 'awaits', 'awakens', 'award', 'away', 'awry', 'ax',
       'babe', 'baby', 'bachelor', 'backdrop', 'background',
       'backgrounds', 'bad', 'bag', 'bahamas', 'bail', 'balance', 'ball',
       'ballet', 'baltimore', 'band', 'bandits', 'bangkok', 'banished',
       'bank', 'banker', 'bankrobber', 'bankrobbery', 'bar', 'barely',
       'bargained', 'barn', 'barney', 'barry', 'barrylevinson',
       'barrysonnenfeld', 'bars', 'base', 'baseball', 'based',
       'basedoncomicbook', 'basedongraphicnovel', 'basedonnovel',
       'basedonplay', 'basedonstagemusical', 'basedontrueevents',
       'basedontruestory', 'basedontvseries', 'basedonvideogame',
       'basedonyoungadultnovel', 'basement', 'basketball', 'batman',
       'battle', 'battlefield', 'battles', 'battling', 'bay', 'beach',
       'bear', 'bears', 'beast', 'beasts', 'beat', 'beating', 'beautiful',
       'beautifulwoman', 'beauty', 'becky', 'becominganadult', 'bed',
       'bedroom', 'bee', 'beer', 'befriends', 'began', 'begin',
       'beginning', 'begins', 'behavior', 'beings', 'belief', 'beliefs',
       'believe', 'believed', 'believes', 'believing', 'beloved', 'ben',
       'benaffleck', 'beneath', 'benfoster', 'beniciodeltoro', 'benjamin',
       'benjaminbratt', 'benkingsley', 'bennett', 'benstiller', 'bent',
       'berlin', 'best', 'bestfriend', 'bet', 'beth', 'betrayal',
       'betrayed', 'bettemidler', 'better', 'betty', 'beverly', 'bible',
       'big', 'bigger', 'biggest', 'biker', 'bikini', 'billhader',
       'billionaire', 'billmurray', 'billnighy', 'billpaxton',
       'billpullman', 'billy', 'billybobthornton', 'billycrudup',
       'billycrystal', 'biography', 'bird', 'birth', 'birthday',
       'bisexual', 'bishop', 'bit', 'bite', 'bitter', 'bizarre', 'black',
       'blackmagic', 'blackmail', 'blackpeople', 'blade', 'blame',
       'blind', 'bliss', 'block', 'blonde', 'blood', 'bloodsplatter',
       'bloodthirsty', 'bloody', 'blow', 'blue', 'board', 'boarding',
       'boardingschool', 'boat', 'bob', 'bobby', 'bobbyfarrelly',
       'bobhoskins', 'bodies', 'body', 'bodyguard', 'bold', 'bollywood',
       'bomb', 'bombing', 'bond', 'bonds', 'bone', 'book', 'books',
       'border', 'bored', 'boredom', 'boring', 'born', 'boss', 'boston',
       'botched', 'bound', 'boundaries', 'bounty', 'bountyhunter',
       'bourne', 'box', 'boxer', 'boxing', 'boy', 'boyfriend', 'boys',
       'bradleycooper', 'bradpitt', 'brain', 'brand', 'brave', 'bravery',
       'brazil', 'brazilian', 'break', 'breakdown', 'breaking', 'breaks',
       'brendanfraser', 'brendangleeson', 'brent', 'brettratner', 'brian',
       'briandepalma', 'bride', 'bridge', 'brief', 'brien', 'bright',
       'brilliant', 'bring', 'bringing', 'brings', 'brink', 'britain',
       'british', 'britishsecretservice', 'brittanymurphy', 'broadway',
       'broke', 'broken', 'broker', 'brooklyn', 'brooks', 'brothel',
       'brother', 'brotherbrotherrelationship', 'brothers',
       'brothersisterrelationship', 'brought', 'brown', 'bruce',
       'brucewillis', 'brutal', 'brutality', 'brutally', 'bryansinger',
       'buck', 'buddies', 'buddy', 'buddycomedy', 'budget', 'build',
       'building', 'built', 'bully', 'bullying', 'bumbling', 'bunny',
       'burglar', 'buried', 'bus', 'bush', 'business', 'businessman',
       'bust', 'busy', 'butcher', 'butler', 'butt', 'buy', 'buzz',
       'cabin', 'caesar', 'cage', 'cairo', 'cal', 'california', 'called',
       'calling', 'calls', 'calvin', 'camcorder', 'came', 'camera',
       'cameraman', 'cameras', 'camerondiaz', 'camp', 'campaign',
       'campbell', 'camping', 'campus', 'canada', 'canadian', 'cancer',
       'candidate', 'candy', 'canine', 'cannibal', 'canuxploitation',
       'capable', 'caper', 'capital', 'capitalism', 'capt', 'captain',
       'captive', 'capture', 'captured', 'captures', 'car', 'caraccident',
       'carchase', 'carcrash', 'card', 'care', 'career', 'carefree',
       'cares', 'caretaker', 'careymulligan', 'caribbean', 'carjourney',
       'carl', 'carlagugino', 'carmen', 'carol', 'carolina', 'carrace',
       'carrie', 'carry', 'carrying', 'cars', 'cartel', 'carter',
       'cartoon', 'caryelwes', 'case', 'caseyaffleck', 'cash', 'casino',
       'cast', 'castle', 'cat', 'cataclysm', 'catastrophe', 'catch',
       'catches', 'cateblanchett', 'catherinekeener', 'catherinezeta',
       'catholic', 'catholicism', 'cattle', 'caught', 'cause', 'caused',
       'causes', 'causing', 'cavalry', 'cave', 'celebrate', 'celebrated',
       'celebration', 'celebrity', 'cellphone', 'cemetery', 'center',
       'centered', 'centers', 'central', 'centuries', 'century',
       'ceremony', 'certain', 'chain', 'chainsaw', 'challenge',
       'challenged', 'challenges', 'champion', 'championship', 'chance',
       'change', 'changed', 'changes', 'changing', 'channingtatum',
       'chaos', 'chaotic', 'chapter', 'character', 'characters', 'charge',
       'charged', 'charismatic', 'charles', 'charlie', 'charliesheen',
       'charlizetheron', 'charlotte', 'charm', 'charming', 'chase',
       'chased', 'chauffeur', 'cheating', 'cheerleader', 'chef',
       'chemical', 'cher', 'chicago', 'chicken', 'chief', 'child',
       'childabuse', 'childhero', 'childhood', 'children', 'chilling',
       'china', 'chinese', 'chip', 'chiwetelejiofor', 'chloe',
       'chloëgracemoretz', 'chloësevigny', 'chocolate', 'choice',
       'choices', 'choose', 'chosen', 'chowyun', 'chris', 'chriscolumbus',
       'chriscooper', 'chrisevans', 'chrishemsworth', 'chrisklein',
       'chrispine', 'chrisrock', 'christ', 'christian', 'christianbale',
       'christianity', 'christianslater', 'christinaapplegate',
       'christinaricci', 'christine', 'christmas', 'christmasparty',
       'christopher', 'christopherlloyd', 'christophernolan',
       'christopherplummer', 'christopherwalken', 'christophwaltz',
       'chronicle', 'chronicles', 'chuck', 'church', 'cia',
       'cigarettesmoking', 'cillianmurphy', 'cinema', 'circle', 'circuit',
       'circumstances', 'circus', 'cities', 'citizens', 'city', 'civil',
       'civilization', 'civilwar', 'claim', 'claims', 'claire',
       'clairedanes', 'clan', 'clark', 'clash', 'class', 'classes',
       'classic', 'classmate', 'classmates', 'classroom',
       'claudevandamme', 'clay', 'clean', 'clear', 'clerk', 'client',
       'clients', 'climate', 'climbing', 'clinteastwood', 'clique',
       'cliveowen', 'clock', 'clone', 'cloning', 'close', 'closed',
       'closer', 'club', 'clubs', 'clues', 'clutches', 'coach', 'coast',
       'cocaine', 'code', 'cody', 'coffin', 'cohen', 'col', 'cold',
       'coldwar', 'cole', 'colin', 'colinfarrell', 'colinfirth',
       'collapse', 'colleague', 'colleagues', 'collect', 'collection',
       'collector', 'college', 'collide', 'collins', 'collision',
       'colonel', 'colony', 'color', 'colorado', 'colorful', 'coma',
       'combat', 'combined', 'come', 'comeback', 'comedian', 'comedic',
       'comedy', 'comes', 'comet', 'comfort', 'comic', 'comics', 'coming',
       'comingofage', 'comingout', 'command', 'commander', 'commercial',
       'commit', 'commitment', 'committed', 'common', 'communication',
       'community', 'companion', 'company', 'compete', 'competing',
       'competition', 'complete', 'completely', 'complex', 'complicated',
       'complications', 'composer', 'computer', 'computervirus', 'conan',
       'concert', 'conclusion', 'condition', 'conditions', 'confederate',
       'confession', 'confidence', 'confident', 'conflict', 'confront',
       'confronted', 'confronts', 'confused', 'congress', 'conman',
       'connected', 'connecticut', 'connection', 'connections',
       'connects', 'connell', 'connie', 'connor', 'conquer', 'conscience',
       'consequences', 'conservative', 'considered', 'conspiracy',
       'conspire', 'constant', 'constantly', 'construction', 'consumed',
       'contact', 'contain', 'contemporary', 'contend', 'contest',
       'continue', 'continues', 'continuing', 'contract', 'control',
       'controlled', 'controlling', 'controversial', 'convention',
       'converge', 'convict', 'convicted', 'convince', 'convinced',
       'convinces', 'cook', 'cooking', 'cool', 'cooper', 'cop', 'cope',
       'cops', 'core', 'corner', 'corners', 'corporate', 'corporation',
       'corpse', 'corrupt', 'corruption', 'cost', 'costume', 'couldn',
       'count', 'country', 'countrymusic', 'countryside', 'county',
       'coup', 'couple', 'couples', 'courage', 'courageous', 'course',
       'court', 'courtcase', 'courteneycox', 'courtroom', 'cousin',
       'cover', 'covert', 'cow', 'cowardliness', 'cowboy', 'crab',
       'crack', 'craig', 'crash', 'crashes', 'crazy', 'create', 'created',
       'creates', 'creation', 'creator', 'creature', 'creatures',
       'credit', 'creepy', 'crew', 'crime', 'crimefighter', 'crimes',
       'criminal', 'criminals', 'crisis', 'critical', 'crocodile',
       'crook', 'crooked', 'cross', 'crossdressing', 'crossed', 'crosses',
       'crown', 'crucifixion', 'cruel', 'cruelty', 'cruise', 'crush',
       'crystal', 'cuba', 'cubagoodingjr', 'cult', 'cultfilm', 'cultural',
       'culture', 'cultureclash', 'cunning', 'cup', 'cure', 'curious',
       'current', 'curse', 'cursed', 'custody', 'customers', 'cut',
       'cyberpunk', 'cyborg', 'dad', 'daily', 'dakotafanning', 'damage',
       'dan', 'danaykroyd', 'dance', 'dancer', 'dancing', 'danger',
       'dangerous', 'dangers', 'daniel', 'danielcraig', 'danielday',
       'danielradcliffe', 'danny', 'dannyboyle', 'dannydevito',
       'dannyglover', 'dare', 'daring', 'dark', 'darkcomedy', 'darkest',
       'darkness', 'date', 'dates', 'dating', 'daughter', 'daughters',
       'dave', 'david', 'davidarquette', 'davidduchovny', 'davidfincher',
       'davidgordongreen', 'davidmorse', 'davido', 'davis', 'daxshepard',
       'day', 'days', 'dc', 'dccomics', 'dea', 'dead', 'deadly', 'deaf',
       'deal', 'dealer', 'dealers', 'dealing', 'deals', 'dean', 'death',
       'deathofafriend', 'deathpenalty', 'deaths', 'debt', 'debut',
       'decade', 'decades', 'decapitation', 'deceased', 'deceit',
       'deception', 'decide', 'decided', 'decides', 'decision',
       'decisions', 'dedicated', 'deeds', 'deep', 'deeper', 'deeply',
       'defeat', 'defend', 'defense', 'deliver', 'delivers', 'delusion',
       'demanding', 'demands', 'demimoore', 'demon', 'demonic',
       'demonicpossession', 'demons', 'dennisdugan', 'dennishopper',
       'dennisquaid', 'dentist', 'denzelwashington', 'department',
       'depressed', 'depression', 'deputy', 'deranged', 'derek',
       'descend', 'desert', 'deserted', 'designed', 'desire', 'desires',
       'desolate', 'despair', 'desperate', 'desperately', 'desperation',
       'despite', 'destined', 'destiny', 'destroy', 'destroyed',
       'destroying', 'destruction', 'details', 'detective', 'detectives',
       'determination', 'determine', 'determined', 'detroit',
       'devastating', 'develop', 'developed', 'develops', 'device',
       'devil', 'devoted', 'diabolical', 'dialogue', 'diamond', 'diane',
       'dianekeaton', 'dianekruger', 'dianelane', 'diary', 'dick',
       'dictator', 'did', 'didn', 'die', 'died', 'diego', 'dies',
       'differences', 'different', 'difficult', 'digging', 'dignity',
       'diner', 'dinner', 'dinosaur', 'dinosaurs', 'dire', 'directed',
       'direction', 'director', 'dirt', 'dirty', 'dirtycop', 'disabled',
       'disappear', 'disappearance', 'disappeared', 'disappears',
       'disaster', 'disastrous', 'discover', 'discovered', 'discovering',
       'discovers', 'discovery', 'disease', 'disfigurement', 'disgraced',
       'disguise', 'dishonesty', 'disillusioned', 'disney', 'disorder',
       'dispatched', 'distant', 'district', 'distrust', 'disturbed',
       'disturbing', 'diva', 'divided', 'division', 'divorce', 'divorced',
       'dj', 'dna', 'doc', 'doctor', 'document', 'documentary',
       'documents', 'does', 'doesn', 'dog', 'dogs', 'doing', 'doll',
       'dollar', 'dollars', 'dolphin', 'dolphlundgren', 'domination',
       'don', 'donaldpetrie', 'donaldsutherland', 'doncheadle', 'donnell',
       'doomed', 'doomsday', 'door', 'doorstep', 'doppelganger',
       'dorothy', 'double', 'doublelife', 'doubt', 'doubts', 'doug',
       'douglas', 'dougliman', 'dr', 'dracula', 'drag', 'dragon', 'drama',
       'dramatic', 'draw', 'drawing', 'drawn', 'draws', 'dream', 'dreams',
       'drew', 'drewbarrymore', 'drifter', 'drink', 'drinking', 'drive',
       'driven', 'driver', 'drives', 'driving', 'drop', 'drowning',
       'drug', 'drugabuse', 'drugaddiction', 'drugdealer', 'druglord',
       'drugs', 'drugtraffic', 'drunk', 'drunken', 'du', 'dualidentity',
       'dude', 'duel', 'duke', 'dumped', 'duo', 'duringcreditsstinger',
       'dustinhoffman', 'dutch', 'duty', 'dwarves', 'dwaynejohnson',
       'dying', 'dyinganddeath', 'dylan', 'dynamic', 'dynasty',
       'dysfunctional', 'dysfunctionalfamily', 'dystopia',
       'dystopicfuture', 'eager', 'earlier', 'early', 'earn', 'earth',
       'earthquake', 'east', 'easy', 'eating', 'eccentric', 'economic',
       'economy', 'eddie', 'eddiegriffin', 'eddiemurphy', 'edge',
       'edharris', 'editor', 'education', 'edward', 'edwardburns',
       'edwardnorton', 'effort', 'efforts', 'egg', 'ego', 'egypt',
       'egyptian', 'el', 'elaborate', 'elderly', 'election', 'elements',
       'eliaskoteas', 'elijahwood', 'eliminate', 'elisabethshue', 'elite',
       'elizabeth', 'elizabethbanks', 'ella', 'ellenburstyn', 'ellenpage',
       'ellie', 'elliot', 'ellis', 'elusive', 'elves', 'elvis', 'embark',
       'embarking', 'embarks', 'embassy', 'embroiled', 'emerge',
       'emergency', 'emerges', 'emilehirsch', 'emily', 'emilyblunt',
       'emilymortimer', 'emilywatson', 'emma', 'emmastone',
       'emmathompson', 'emmawatson', 'emotional', 'emotionally',
       'emotions', 'emperor', 'empire', 'employee', 'employees',
       'employer', 'employs', 'encounter', 'encounters', 'end', 'ended',
       'ending', 'endless', 'endoftheworld', 'ends', 'enemies', 'enemy',
       'energy', 'enforcement', 'engaged', 'engagement', 'engineer',
       'england', 'english', 'enigmatic', 'enjoy', 'enlist', 'enlists',
       'enormous', 'ensemblecast', 'ensues', 'entangled', 'enter',
       'enterprise', 'enters', 'entertainer', 'entertaining', 'entire',
       'entirely', 'entity', 'environment', 'environmental', 'epic',
       'epidemic', 'era', 'eric', 'ericbana', 'erin', 'ernest',
       'eroticism', 'erupts', 'escapade', 'escape', 'escaped',
       'escapefromprison', 'escapes', 'escaping', 'escort', 'especially',
       'espionage', 'establishment', 'estate', 'estranged', 'eternal',
       'ethan', 'ethanhawke', 'eugenelevy', 'europe', 'european', 'eva',
       'evacuation', 'evade', 'evamendes', 'evanrachelwood', 'eve',
       'evening', 'event', 'events', 'eventually', 'everybody',
       'everyday', 'evidence', 'evil', 'evolution', 'ewanmcgregor', 'ex',
       'exact', 'exactly', 'examines', 'exchange', 'exciting',
       'exclusive', 'execution', 'executive', 'exercise', 'exist',
       'existed', 'existence', 'existentialism', 'exists', 'exorcism',
       'exotic', 'exoticisland', 'expectations', 'expected', 'expects',
       'expedition', 'experience', 'experienced', 'experiences',

In [39]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [40]:
stem("'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'")

"'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'"

In [41]:
movies['tags'] = movies['tags'].apply(stem)

In [42]:
list(cv.get_feature_names_out())

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '18thcentury',
 '19',
 '1930s',
 '1940s',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultanimation',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affect',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'alienplanet',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymity',
 'answer',
 'answers',
 'ant',
 'antarctic',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeology',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrangement',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'article',
 'artificial',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashes',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'bourne',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butcher',
 'butler',
 'butt',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calling',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'canine',
 'cannibal',
 'canuxploitation',
 'capable',
 'caper',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'cares',
 'caretaker',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceremony',
 'certain',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chauffeur',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christopher',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closed',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confederate',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confronts',
 'confused',
 'congress',
 'conman',
 'connected',
 'connecticut',
 'connection',
 'connections',
 'connects',
 'connell',
 'connie',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 ...]

In [43]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [44]:
print(similarity.shape)

(4806, 4806)

In [45]:
print(type(similarity))

<class 'numpy.ndarray'>

In [46]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1]) #with enumerate the index and the value of the similarity is given in a list of tuples and index is held in the first element and the value of similarity is held in the second element of the tuple

[(0, np.float64(1.0000000000000002)),
 (539, np.float64(0.25038669783359574)),
 (1192, np.float64(0.24779731389167606)),
 (507, np.float64(0.24283093212859141)),
 (260, np.float64(0.2409900932515112)),
 (1214, np.float64(0.23939494881986934)),
 (1916, np.float64(0.233785950059759)),
 (582, np.float64(0.23174488732966075)),
 (1202, np.float64(0.23084512921915967)),
 (2405, np.float64(0.23084512921915967)),
 (3728, np.float64(0.2294157338705618)),
 (1440, np.float64(0.21677749238103003)),
 (322, np.float64(0.21629522817435)),
 (74, np.float64(0.21526419295572297)),
 (3606, np.float64(0.21486752129677)),
 (83, np.float64(0.21296183592613546)),
 (61, np.float64(0.21239769762143662)),
 (4190, np.float64(0.21239769762143662)),
 (1533, np.float64(0.2108663315950723)),
 (2329, np.float64(0.20857039859669468)),
 (47, np.float64(0.20770324619863198)),
 (495, np.float64(0.20751433915982237)),
 (942, np.float64(0.20395079136182276)),
 (972, np.float64(0.20395079136182276)),
 (466, np.float64(0.2029530274475215)),
 (1327, np.float64(0.2029530274475215)),
 (2969, np.float64(0.2024645717996314)),
 (2200, np.float64(0.19767387315371682)),
 (1199, np.float64(0.19466570535691505)),
 (973, np.float64(0.19194297398747862)),
 (151, np.float64(0.19117977822546817)),
 (1273, np.float64(0.19088542889273336)),
 (2782, np.float64(0.19088542889273336)),
 (4046, np.float64(0.18848425873126295)),
 (2997, np.float64(0.18731716231633883)),
 (4405, np.float64(0.18731716231633883)),
 (305, np.float64(0.18541926977182405)),
 (3160, np.float64(0.1853959098637286)),
 (3536, np.float64(0.1842105263157895)),
 (27, np.float64(0.18172434016970185)),
 (3325, np.float64(0.1813690625275029)),
 (150, np.float64(0.1810898182317451)),
 (220, np.float64(0.18074256993863339)),
 (931, np.float64(0.18074256993863339)),
 (300, np.float64(0.17954621161490197)),
 (1069, np.float64(0.17954621161490197)),
 (4, np.float64(0.177343107178349)),
 (36, np.float64(0.177343107178349)),
 (461, np.float64(0.17699808135119718)),
 (1319, np.float64(0.17699808135119718)),
 (184, np.float64(0.17521916101261562)),
 (301, np.float64(0.1745025152241333)),
 (67, np.float64(0.17206180040292132)),
 (46, np.float64(0.16943474841747155)),
 (7, np.float64(0.1692777916923361)),
 (373, np.float64(0.1691275228729346)),
 (1827, np.float64(0.16742770563222897)),
 (2492, np.float64(0.16556654463313053)),
 (2727, np.float64(0.16556654463313053)),
 (149, np.float64(0.16481712868606585)),
 (26, np.float64(0.16452254913212452)),
 (1342, np.float64(0.16452254913212452)),
 (661, np.float64(0.16350382386265752)),
 (208, np.float64(0.16222142113076254)),
 (838, np.float64(0.16222142113076254)),
 (4008, np.float64(0.16222142113076254)),
 (108, np.float64(0.16222142113076252)),
 (1804, np.float64(0.16222142113076252)),
 (94, np.float64(0.15907119074394446)),
 (2511, np.float64(0.15907119074394446)),
 (52, np.float64(0.15789473684210528)),
 (1392, np.float64(0.15747244473304667)),
 (31, np.float64(0.15609763526361567)),
 (581, np.float64(0.15609763526361567)),
 (1295, np.float64(0.15585730003983933)),
 (1379, np.float64(0.15585730003983933)),
 (4336, np.float64(0.15389675281277312)),
 (91, np.float64(0.15328483487124145)),
 (168, np.float64(0.152008377581442)),
 (3626, np.float64(0.15061880828219448)),
 (311, np.float64(0.15018785229652765)),
 (1961, np.float64(0.14910501299480672)),
 (577, np.float64(0.14808721943977307)),
 (3352, np.float64(0.14808721943977307)),
 (158, np.float64(0.14673479641335554)),
 (502, np.float64(0.14673479641335554)),
 (111, np.float64(0.14567913668701626)),
 (2165, np.float64(0.14567913668701626)),
 (1353, np.float64(0.14509525002200235)),
 (172, np.float64(0.14509525002200233)),
 (490, np.float64(0.14509525002200233)),
 (17, np.float64(0.1442149876003076)),
 (1934, np.float64(0.14350946197048198)),
 (1176, np.float64(0.1433848336691011)),
 (422, np.float64(0.14159846508095775)),
 (505, np.float64(0.14159846508095775)),
 (1484, np.float64(0.14159846508095775)),
 (557, np.float64(0.1411956236812263)),
 (41, np.float64(0.1404878717372541)),
 (84, np.float64(0.13977653617040256)),
 (369, np.float64(0.1391037210186643)),
 (568, np.float64(0.1391037210186643)),
 (2682, np.float64(0.1391037210186643)),
 (56, np.float64(0.13834289277321493)),
 (249, np.float64(0.13834289277321493)),
 (1325, np.float64(0.13834289277321493)),
 (1320, np.float64(0.13764944032233709)),
 (332, np.float64(0.13710212427677043)),
 (1218, np.float64(0.13710212427677043)),
 (487, np.float64(0.13530201829834768)),
 (2580, np.float64(0.13530201829834768)),
 (3997, np.float64(0.13530201829834768)),
 (187, np.float64(0.13518451760896877)),
 (413, np.float64(0.13518451760896877)),
 (1669, np.float64(0.13497638119975428)),
 (4348, np.float64(0.13497638119975428)),
 (2129, np.float64(0.13369695534647594)),
 (2869, np.float64(0.13369695534647594)),
 (1941, np.float64(0.13334518676566626)),
 (2616, np.float64(0.1324532357065044)),
 (2968, np.float64(0.1324532357065044)),
 (4490, np.float64(0.1324532357065044)),
 (595, np.float64(0.13157894736842107)),
 (1013, np.float64(0.13157894736842107)),
 (1297, np.float64(0.13157894736842107)),
 (3407, np.float64(0.13157894736842107)),
 (3620, np.float64(0.13157894736842107)),
 (127, np.float64(0.13112201362143713)),
 (342, np.float64(0.1302565123238377)),
 (2476, np.float64(0.130066495428618)),
 (754, np.float64(0.12988108336653278)),
 (1475, np.float64(0.12988108336653278)),
 (68, np.float64(0.12977713690461004)),
 (134, np.float64(0.12977713690461004)),
 (368, np.float64(0.12977713690461004)),
 (1156, np.float64(0.12977713690461004)),
 (1000, np.float64(0.12892051277806202)),
 (3671, np.float64(0.12824729401064427)),
 (1045, np.float64(0.12725695259515557)),
 (1094, np.float64(0.12725695259515557)),
 (1743, np.float64(0.12725695259515557)),
 (2374, np.float64(0.12725695259515557)),
 (3374, np.float64(0.12725695259515557)),
 (740, np.float64(0.126673647984535)),
 (1613, np.float64(0.126673647984535)),
 (1571, np.float64(0.12565617248750865)),
 (1711, np.float64(0.12565617248750865)),
 (529, np.float64(0.12515654358043973)),
 (778, np.float64(0.12515654358043973)),
 (483, np.float64(0.12487810821089254)),
 (1654, np.float64(0.12487810821089254)),
 (420, np.float64(0.12369267399882337)),
 (1035, np.float64(0.12369267399882337)),
 (3441, np.float64(0.12369267399882337)),
 (1829, np.float64(0.12262786789699316)),
 (4673, np.float64(0.12262786789699316)),
 (939, np.float64(0.12262786789699313)),
 (1737, np.float64(0.12262786789699313)),
 (228, np.float64(0.12227899701112963)),
 (279, np.float64(0.12227899701112963)),
 (2709, np.float64(0.12227899701112963)),
 (3307, np.float64(0.12227899701112963)),
 (3405, np.float64(0.12227899701112963)),
 (3216, np.float64(0.12166606584807191)),
 (278, np.float64(0.12091270835166862)),
 (432, np.float64(0.12091270835166862)),
 (549, np.float64(0.12091270835166862)),
 (28, np.float64(0.1204950466257556)),
 (1272, np.float64(0.1204950466257556)),
 (2071, np.float64(0.1204950466257556)),
 (238, np.float64(0.11980845957463077)),
 (95, np.float64(0.11959121830873498)),
 (454, np.float64(0.11959121830873498)),
 (72, np.float64(0.11846977555181847)),
 (275, np.float64(0.11846977555181847)),
 (579, np.float64(0.11846977555181847)),
 (2864, np.float64(0.11846977555181847)),
 (123, np.float64(0.11831213107007527)),
 (1508, np.float64(0.11831213107007527)),
 (2543, np.float64(0.11831213107007527)),
 (653, np.float64(0.11803342130469505)),
 (808, np.float64(0.11803342130469505)),
 (3145, np.float64(0.11803342130469505)),
 (4201, np.float64(0.11803342130469505)),
 (50, np.float64(0.116543309349613)),
 (1978, np.float64(0.116543309349613)),
 (692, np.float64(0.11587244366483038)),
 (1275, np.float64(0.11587244366483038)),
 (3628, np.float64(0.11587244366483038)),
 (169, np.float64(0.1147078669352809)),
 (624, np.float64(0.1147078669352809)),
 (166, np.float64(0.11470786693528087)),
 (232, np.float64(0.11470786693528087)),
 (294, np.float64(0.11470786693528087)),
 (859, np.float64(0.11470786693528087)),
 (1612, np.float64(0.11470786693528087)),
 (1570, np.float64(0.1139194873735864)),
 (5, np.float64(0.11357771260606365)),
 (199, np.float64(0.11357771260606365)),
 (206, np.float64(0.11357771260606365)),
 (10, np.float64(0.11295649894498103)),
 (87, np.float64(0.11295649894498103)),
 (513, np.float64(0.11295649894498103)),
 (687, np.float64(0.11295649894498103)),
 (1029, np.float64(0.11295649894498103)),
 (3006, np.float64(0.11295649894498103)),
 (81, np.float64(0.11239029738980326)),
 (627, np.float64(0.11164843913471803)),
 (1299, np.float64(0.11164843913471803)),
 (1369, np.float64(0.11164843913471803)),
 (1723, np.float64(0.11164843913471803)),
 (2255, np.float64(0.11164843913471803)),
 (2319, np.float64(0.11164843913471803)),
 (3719, np.float64(0.11164843913471803)),
 (3998, np.float64(0.11164843913471803)),
 (126, np.float64(0.11128297681493143)),
 (508, np.float64(0.11128297681493143)),
 (2446, np.float64(0.11128297681493143)),
 (2579, np.float64(0.11128297681493143)),
 (777, np.float64(0.11037769642208699)),
 (14, np.float64(0.10968169942141635)),
 (854, np.float64(0.10968169942141635)),
 (900, np.float64(0.10968169942141635)),
 (1193, np.float64(0.10968169942141635)),
 (3496, np.float64(0.10968169942141635)),
 (141, np.float64(0.10882143751650175)),
 (1520, np.float64(0.10882143751650175)),
 (1717, np.float64(0.10882143751650175)),
 (2630, np.float64(0.10882143751650175)),
 (3659, np.float64(0.10882143751650175)),
 (4016, np.float64(0.10882143751650175)),
 (4133, np.float64(0.10882143751650175)),
 (1017, np.float64(0.10838874619051501)),
 (1493, np.float64(0.10838874619051501)),
 (2102, np.float64(0.10838874619051501)),
 (2435, np.float64(0.10838874619051501)),
 (2756, np.float64(0.10838874619051501)),
 (312, np.float64(0.10814761408717502)),
 (1080, np.float64(0.10814761408717502)),
 (1292, np.float64(0.10814761408717502)),
 (2009, np.float64(0.10814761408717502)),
 (3338, np.float64(0.10814761408717502)),
 (3618, np.float64(0.10814761408717502)),
 (4095, np.float64(0.10814761408717502)),
 (18, np.float64(0.10743376064838502)),
 (102, np.float64(0.10743376064838502)),
 (131, np.float64(0.106676149412533)),
 (174, np.float64(0.106676149412533)),
 (266, np.float64(0.106676149412533)),
 (2068, np.float64(0.106676149412533)),
 (239, np.float64(0.10650358071057624)),
 (403, np.float64(0.10650358071057624)),
 (233, np.float64(0.10619884881071831)),
 (325, np.float64(0.10619884881071831)),
 (773, np.float64(0.10619884881071831)),
 (1154, np.float64(0.10619884881071831)),
 (3053, np.float64(0.10619884881071831)),
 (3779, np.float64(0.10619884881071831)),
 (3837, np.float64(0.10619884881071831)),
 (3952, np.float64(0.10619884881071831)),
 (295, np.float64(0.10526315789473685)),
 (330, np.float64(0.10526315789473685)),
 (535, np.float64(0.10526315789473685)),
 (986, np.float64(0.10526315789473685)),
 (1271, np.float64(0.10526315789473685)),
 (2177, np.float64(0.10526315789473685)),
 (3100, np.float64(0.10526315789473685)),
 (4077, np.float64(0.10526315789473685)),
 (4228, np.float64(0.10526315789473685)),
 (182, np.float64(0.10390486669322622)),
 (139, np.float64(0.10385162309931599)),
 (105, np.float64(0.1037571695799112)),
 (476, np.float64(0.1037571695799112)),
 (2452, np.float64(0.1037571695799112)),
 (2558, np.float64(0.1037571695799112)),
 (2758, np.float64(0.1037571695799112)),
 (4196, np.float64(0.1037571695799112)),
 (4545, np.float64(0.10301070542879115)),
 (334, np.float64(0.10259783520851541)),
 (643, np.float64(0.10259783520851541)),
 (1054, np.float64(0.10259783520851541)),
 (3781, np.float64(0.10259783520851541)),
 (85, np.float64(0.10203255357771539)),
 (33, np.float64(0.10147651372376076)),
 (148, np.float64(0.10147651372376076)),
 (157, np.float64(0.10147651372376076)),
 (263, np.float64(0.10147651372376076)),
 (715, np.float64(0.10147651372376076)),
 (935, np.float64(0.10147651372376076)),
 (1278, np.float64(0.10147651372376076)),
 (1497, np.float64(0.10147651372376076)),
 (2517, np.float64(0.10147651372376076)),
 (2656, np.float64(0.10147651372376076)),
 (4331, np.float64(0.10147651372376076)),
 (129, np.float64(0.101338918387628)),
 (510, np.float64(0.101338918387628)),
 (898, np.float64(0.101338918387628)),
 (1084, np.float64(0.101338918387628)),
 (1107, np.float64(0.101338918387628)),
 (3462, np.float64(0.101338918387628)),
 (307, np.float64(0.1003911722115382)),
 (587, np.float64(0.10012523486435178)),
 (1231, np.float64(0.10012523486435178)),
 (4043, np.float64(0.10012523486435178)),
 (35, np.float64(0.09933992677987831)),
 (400, np.float64(0.09933992677987831)),
 (660, np.float64(0.09933992677987831)),
 (781, np.float64(0.09933992677987831)),
 (1938, np.float64(0.09933992677987831)),
 (2657, np.float64(0.09933992677987831)),
 (4254, np.float64(0.09933992677987831)),
 (4623, np.float64(0.09933992677987831)),
 (371, np.float64(0.0989541391990587)),
 (412, np.float64(0.0989541391990587)),
 (473, np.float64(0.0989541391990587)),
 (870, np.float64(0.0989541391990587)),
 (1200, np.float64(0.0989541391990587)),
 (1435, np.float64(0.0989541391990587)),
 (2592, np.float64(0.0989541391990587)),
 (270, np.float64(0.0978231976089037)),
 (410, np.float64(0.0978231976089037)),
 (813, np.float64(0.0978231976089037)),
 (933, np.float64(0.0978231976089037)),
 (1274, np.float64(0.0978231976089037)),
 (1819, np.float64(0.0978231976089037)),
 (1842, np.float64(0.0978231976089037)),
 (2280, np.float64(0.0978231976089037)),
 (292, np.float64(0.09733285267845754)),
 (389, np.float64(0.09733285267845754)),
 (530, np.float64(0.09733285267845754)),
 (691, np.float64(0.09733285267845754)),
 (791, np.float64(0.09733285267845754)),
 (920, np.float64(0.09733285267845754)),
 (1075, np.float64(0.09733285267845754)),
 (2647, np.float64(0.09733285267845754)),
 (3091, np.float64(0.09733285267845754)),
 (3734, np.float64(0.09733285267845754)),
 (1087, np.float64(0.09694584179118516)),
 (1999, np.float64(0.0967301666813349)),
 (243, np.float64(0.09567297464698798)),
 (785, np.float64(0.09558988911273408)),
 (122, np.float64(0.09544271444636668)),
 (564, np.float64(0.09544271444636668)),
 (1404, np.float64(0.09544271444636668)),
 (1470, np.float64(0.09544271444636668)),
 (1585, np.float64(0.09544271444636668)),
 (1682, np.float64(0.09544271444636668)),
 (1752, np.float64(0.09544271444636668)),
 (589, np.float64(0.09464970485606021)),
 (618, np.float64(0.09464970485606021)),
 (1355, np.float64(0.09464970485606021)),
 (12, np.float64(0.09365858115816941)),
 (23, np.float64(0.09365858115816941)),
 (43, np.float64(0.09365858115816941)),
 (142, np.float64(0.09365858115816941)),
 (236, np.float64(0.09365858115816941)),
 (362, np.float64(0.09365858115816941)),
 (2089, np.float64(0.09365858115816941)),
 (2392, np.float64(0.09365858115816941)),
 (2648, np.float64(0.09365858115816941)),
 (2792, np.float64(0.09365858115816941)),
 (160, np.float64(0.09304036594559835)),
 (596, np.float64(0.09269795493186431)),
 (1414, np.float64(0.09269795493186431)),
 (2484, np.float64(0.09269795493186431)),
 (511, np.float64(0.09197090092274487)),
 (922, np.float64(0.09197090092274487)),
 (1025, np.float64(0.09197090092274487)),
 (1304, np.float64(0.09197090092274487)),
 (2813, np.float64(0.09197090092274487)),
 (2836, np.float64(0.09197090092274487)),
 (3426, np.float64(0.09197090092274487)),
 (479, np.float64(0.09183979479633063)),
 (1828, np.float64(0.09176629354822471)),
 (1920, np.float64(0.09176629354822471)),
 (1276, np.float64(0.09086217008485092)),
 (1492, np.float64(0.09086217008485092)),
 (112, np.float64(0.09037128496931669)),
 (164, np.float64(0.09037128496931669)),
 (242, np.float64(0.09037128496931669)),
 (794, np.float64(0.09037128496931669)),
 (960, np.float64(0.09037128496931669)),
 (978, np.float64(0.09037128496931669)),
 (1002, np.float64(0.09037128496931669)),
 (1247, np.float64(0.09037128496931669)),
 (4468, np.float64(0.09037128496931669)),
 (799, np.float64(0.09012301173931252)),
 (2270, np.float64(0.08998425413316952)),
 (2384, np.float64(0.08998425413316952)),
 (2852, np.float64(0.08998425413316952)),
 (3152, np.float64(0.08998425413316952)),
 (4353, np.float64(0.08998425413316952)),
 (4502, np.float64(0.08998425413316952)),
 (4516, np.float64(0.08998425413316952)),
 (4654, np.float64(0.08998425413316952)),
 (2966, np.float64(0.0891313035643173)),
 (2444, np.float64(0.08903057122447033)),
 (21, np.float64(0.08885233166386385)),
 (227, np.float64(0.08885233166386385)),
 (306, np.float64(0.08885233166386385)),
 (349, np.float64(0.08885233166386385)),
 (356, np.float64(0.08885233166386385)),
 (775, np.float64(0.08885233166386385)),
 (901, np.float64(0.08885233166386385)),
 (1374, np.float64(0.08885233166386385)),
 (1696, np.float64(0.08885233166386385)),
 (1786, np.float64(0.08885233166386385)),
 (2163, np.float64(0.08885233166386385)),
 (3535, np.float64(0.08885233166386385)),
 (3814, np.float64(0.08885233166386385)),
 (4626, np.float64(0.08885233166386385)),
 (63, np.float64(0.08830215713766959)),
 (107, np.float64(0.08830215713766959)),
 (170, np.float64(0.08830215713766959)),
 (363, np.float64(0.08830215713766959)),
 (541, np.float64(0.08830215713766959)),
 (812, np.float64(0.08830215713766959)),
 (2001, np.float64(0.08830215713766959)),
 (32, np.float64(0.08749572785196143)),
 (45, np.float64(0.08749572785196143)),
 (222, np.float64(0.08749572785196143)),
 (467, np.float64(0.08749572785196143)),
 (1, np.float64(0.08740748201220976)),
 (75, np.float64(0.08740748201220976)),
 (88, np.float64(0.08740748201220976)),
 (121, np.float64(0.08740748201220976)),
 (245, np.float64(0.08740748201220976)),
 (315, np.float64(0.08740748201220976)),
 (626, np.float64(0.08740748201220976)),
 (786, np.float64(0.08740748201220976)),
 (894, np.float64(0.08740748201220976)),
 (937, np.float64(0.08740748201220976)),
 (3299, np.float64(0.08740748201220976)),
 (3447, np.float64(0.08740748201220976)),
 (230, np.float64(0.08671099695241201)),
 (381, np.float64(0.08671099695241201)),
 (1137, np.float64(0.08671099695241201)),
 (2494, np.float64(0.08671099695241201)),
 (2876, np.float64(0.08671099695241201)),
 (4163, np.float64(0.08671099695241201)),
 (4737, np.float64(0.08671099695241201)),
 (2382, np.float64(0.08646430798325933)),
 (86, np.float64(0.08603090020146065)),
 (96, np.float64(0.08603090020146065)),
 (814, np.float64(0.08603090020146065)),
 (1111, np.float64(0.08603090020146065)),
 (1140, np.float64(0.08603090020146065)),
 (1267, np.float64(0.08603090020146065)),
 (2243, np.float64(0.08603090020146065)),
 (2247, np.float64(0.08603090020146065)),
 (2790, np.float64(0.08603090020146065)),
 (3089, np.float64(0.08603090020146065)),
 (4257, np.float64(0.08603090020146065)),
 (4657, np.float64(0.08603090020146065)),
 (654, np.float64(0.08594700851870801)),
 (1280, np.float64(0.08594700851870801)),
 (1874, np.float64(0.08594700851870801)),
 (103, np.float64(0.08520286456846099)),
 (39, np.float64(0.08471737420873576)),
 (101, np.float64(0.08471737420873576)),
 (203, np.float64(0.08471737420873576)),
 (457, np.float64(0.08471737420873576)),
 (547, np.float64(0.08471737420873576)),
 (899, np.float64(0.08471737420873576)),
 (1205, np.float64(0.08471737420873576)),
 (1469, np.float64(0.08471737420873576)),
 (1519, np.float64(0.08471737420873576)),
 (2300, np.float64(0.08471737420873576)),
 (3233, np.float64(0.08471737420873576)),
 (3908, np.float64(0.08471737420873576)),
 (193, np.float64(0.08447772061910234)),
 (491, np.float64(0.08447772061910234)),
 (501, np.float64(0.08447772061910234)),
 (1824, np.float64(0.08447772061910234)),
 (3439, np.float64(0.08447772061910234)),
 (1401, np.float64(0.0837707816583391)),
 (1617, np.float64(0.0837707816583391)),
 (2246, np.float64(0.0837707816583391)),
 (2335, np.float64(0.0837707816583391)),
 (3067, np.float64(0.0837707816583391)),
 (4492, np.float64(0.0837707816583391)),
 (4718, np.float64(0.0837707816583391)),
 (257, np.float64(0.08346223261119858)),
 (634, np.float64(0.08346223261119858)),
 (746, np.float64(0.08346223261119858)),

In [47]:
def recommend(movie):
    movie_index=movies[movies['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [48]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman
Batman & Robin

In [49]:
import joblib 
joblib.dump(movies,'movies.pkl')

['movies.pkl']

In [50]:
joblib.dump(similarity,'similarity.pkl')

['similarity.pkl']